apiVersion: v1
kind: Namespace
metadata:
  name: tkc-workload
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: all:psp:privileged
roleRef:
  kind: ClusterRole
  name: psp:vmware-system-privileged
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nvidia-plugin-test
  namespace: tkc-workload
  labels:
    app: nvidia-plugin-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nvidia-plugin-test
  template:
    metadata:
      labels:
        app: nvidia-plugin-test
    spec:
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      containers:
        - name: nvidia-plugin-test-ctr
          image: nvcr.io/nvidia/cloud-native/gpu-operator-validator:v1.10.1
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c']
          args:
            - "while true;  do vectorAdd & nvidia-smi & wait; sleep 30; done"
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            limits:
              nvidia.com/gpu: 1
      nodeSelector: # Schedule on the node with GPU sharing enabled
          nvidia.com/gpu.product: GRID-V100-4C


